### ISSUE TITLE
Add SSO configuration for relevant batteries

### ISSUE THREAD

**Issue by JTarasovic** [batteries-included/batteries-included#50]
Now that we have the ability to create Keycloak clients, we need to add the necessary configuration for each battery that makes sense to have SSO enabled for.

- [x] batteries-included/main#2128 
- [x] batteries-included/main#2131 
- [x] batteries-included/main#2375
- [ ] ~k8s cluster itself?~
- [x] batteries-included/batteries-included#52 
- [x] batteries-included/batteries-included#38

probably need proxy or similar
- [x] batteries-included/main#2483
- [x] batteries-included/main#2344 
- [x] batteries-included/main#2562
- [ ] ~loki~
- [ ] ~postgres?~
- [ ] ~redis?~
- [ ] ~trivy?~
